GET http://localhost:3000/

###
GET http://localhost:3000/api/persons

###
GET http://localhost:3000/api/persons/65405b368a4b0f6ec6bcde38

###
DELETE http://localhost:3000/api/persons/6543a57f55ea568b6d0d61c8

###
POST http://localhost:3000/api/persons
Content-Type: application/json

{
  "name": "Ronny Parra Guerrero",
  "number": "0998264721"
}

###
//testing displayed url in fly.io

GET https://nodeexpress.fly.dev/

###
GET https://nodeexpress.fly.dev/api/persons

###
GET https://nodeexpress.fly.dev/api/persons/3

###
DELETE https://nodeexpress.fly.dev/api/persons/5

###
POST https://nodeexpress.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Roger Federer",
  "number": "0998265466"
}
